site_name: Debrid Unlimited Media Bridge
site_description: DUMB Documentation
site_author: DUMB Team
site_url: "https://I-am-PUID-0.github.io/DUMB"
repo_name: "I-am-PUID-0/DUMB"
repo_url: "https://github.com/I-am-PUID-0/DUMB"
edit_uri: "https://github.com/I-am-PUID-0/DUMB_Docs/edit/master/docs/"


nav:
  - Home: index.md
  - Features:
      - Overview: features/index.md
      - Configuration: features/configuration.md
      - Usage: features/usage.md  
  - Getting Started:
      - Introduction: getting-started/index.md
      - Installation: getting-started/installation.md
  - Services:
      - Overview: services/index.md
      - DUMB:
        - Overview: services/dumb/index.md
        - DUMB API: services/dumb/api.md
        - DUMB Frontend: services/dumb/dumb-frontend.md
      - Core:
        - Overview: services/core/index.md
        - CLI Debrid: services/core/cli-debrid.md
        - Decypharr: services/core/decypharr.md
        - NzbDAV: services/core/nzbdav.md
        - Plex Media Server: services/core/plex-media-server.md
        - Jellyfin: services/core/jellyfin.md
        - Emby: services/core/emby.md
        - Plex Debrid: services/core/plex-debrid.md
        - Riven Backend: services/core/riven-backend.md
        - Sonarr: services/core/sonarr.md
        - Radarr: services/core/radarr.md
        - Lidarr: services/core/lidarr.md
        - Prowlarr: services/core/prowlarr.md
        - Whisparr: services/core/whisparr.md
      - Dependent:
        - Overview: services/dependent/index.md
        - CLI Battery: services/dependent/cli-battery.md
        - Phalanx DB: services/dependent/phalanx-db.md
        - PostgreSQL: services/dependent/postgres.md
        - rclone: services/dependent/rclone.md
        - zurg: services/dependent/zurg.md
      - Optional:
        - Overview: services/optional/index.md
        - pgAdmin: services/optional/pgadmin.md        
        - Riven Frontend: services/optional/riven-frontend.md
        - Zilean: services/optional/zilean.md
  - Deployment:
      - Overview: deployment/index.md
      - Docker: deployment/docker.md
      - Portainer: deployment/portainer.md 
      - Unraid: deployment/unraid.md     
      - WSL: deployment/wsl.md
      - Proxmox: deployment/proxmox.md
      - Synology: deployment/synology.md
      - QNAP: deployment/qnap.md
      - TrueNAS: deployment/truenas.md
      - Dockge: deployment/dockge.md
  - API:
      - Overview: api/index.md
      - Health: api/health.md
      - Process Management: api/process.md
      - Configuration: api/config.md
      - Logs: api/logs.md
      - Real-Time WebSocket Logs: api/websocket_logs.md
  - FAQ: 
      - General: faq/general.md
      - DUMB: faq/dumb.md
      - Decypharr: faq/decypharr.md      
      - CLI Debrid: faq/cli-debrid.md
      - Plex: faq/plex.md
      - Plex Debrid: faq/plex-debrid.md
      - pgAdmin: faq/pgadmin.md
      - PostgreSQL: faq/postgres.md
      - rclone: faq/rclone.md
      - Riven: faq/riven.md
      - Zilean: faq/zilean.md
      - Zurg: faq/zurg.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - About: about.md

theme:
  name: material
  logo: assets/images/DUMB.png
  favicon: assets/images/favicon.ico
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top 
    - navigation.footer
    - navigation.sections
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate 

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/moon-star
        name: Switch to system preference
    


  generator: false

extra_javascript:
  - https://cdn.jsdelivr.net/npm/medium-zoom@1.1.0/dist/medium-zoom.min.js
  - assets/js/zoom.js
  - assets/js/github-meta.js

extra_css:
  - assets/css/main.css

extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/I-am-PUID-0/DUMB
    - icon: fontawesome/brands/discord
      link: https://discord.gg/8dqKUBtbp5
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/iampuid0/dumb
      
  generator: false

plugins:
  - search
  - tags

markdown_extensions:
  - abbr
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - tables
  - codehilite:
      linenums: false
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # - pymdownx.blocks.admonition
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.keys 
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "#"  
